import { randomUUID } from "node:crypto";
import { createWriteStream } from "node:fs";
import { mkdir, rm, stat } from "node:fs/promises";
import path from "node:path";
import archiver from "archiver";
import type {
  BuildPackageInput,
  BuildPackageOutput,
  ImagerySourceDef,
  ImageryAdapter,
  JobProgress,
  ManifestEntry,
  MapFeature,
} from "../types.js";
import { writeGeoPackage } from "./gpkg-writer.js";
import { buildGrgKmz } from "./grg-kmz.js";
import { buildManifestXml } from "./manifest.js";
import { buildCotEvents } from "./cot-writer.js";
import { buildKmlDocument } from "./kml-writer.js";
import { buildMapSourceXml } from "./mapsource-xml.js";

/**
 * Package builder — orchestrates imagery fetch, writers, manifest, and the
 * final data-package zip. All zip entry names use FORWARD slashes (ATAK
 * requires manifest zipEntry to byte-match zip paths).
 */

const TILE_FAIL_WARN_RATIO = 0.2;
const TILE_FAIL_ABORT_RATIO = 0.6;

interface ZipFile {
  /** Forward-slash zip entry path. */
  entry: string;
  content: Buffer | string | { file: string };
}

/** Filename-safe form of the package name (zip-inner file base names). */
function safeFileBase(name: string): string {
  const base = name.trim().replace(/[^A-Za-z0-9._-]+/g, "_").replace(/^_+|_+$/g, "");
  return base.length > 0 ? base : "package";
}

/** SQL-identifier-safe gpkg table name derived from the package name. */
function safeTableName(name: string): string {
  let t = name.toLowerCase().replace(/[^a-z0-9_]+/g, "_").replace(/^_+|_+$/g, "");
  if (!/^[a-z_]/.test(t)) t = `t_${t}`;
  return t.length > 0 ? t : "tiles";
}

function resolveSource(
  catalog: ImagerySourceDef[],
  sourceId: string,
): ImagerySourceDef {
  const source = catalog.find((s) => s.id === sourceId);
  if (!source) throw new Error(`Unknown imagery source: ${sourceId}`);
  return source;
}

function attributionText(
  packageName: string,
  sources: ImagerySourceDef[],
  now: Date,
): string {
  const lines: string[] = [
    packageName,
    `Generated by TAKPack Studio on ${now.toISOString()}`,
    "",
  ];
  for (const s of sources) {
    lines.push(s.name, `Attribution: ${s.attribution}`, `License: ${s.license}`, "");
  }
  return lines.join("\n");
}

async function writeZip(zipPath: string, files: ZipFile[]): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    const out = createWriteStream(zipPath);
    const archive = archiver("zip", { zlib: { level: 6 } });
    out.on("close", resolve);
    out.on("error", reject);
    archive.on("error", reject);
    archive.pipe(out);
    for (const f of files) {
      if (typeof f.content === "object" && !Buffer.isBuffer(f.content)) {
        archive.file(f.content.file, { name: f.entry });
      } else {
        archive.append(f.content, { name: f.entry });
      }
    }
    void archive.finalize();
  });
}

export async function buildPackage(
  input: BuildPackageInput,
): Promise<BuildPackageOutput> {
  const { request, jobId, outDir, catalog, adapters, limits, onProgress, signal } =
    input;
  const uuid = input.determinism?.uuid ?? randomUUID;
  const nowFn = input.determinism?.now ?? (() => new Date());

  const checkAborted = (): void => {
    if (signal?.aborted) throw new Error("Export aborted");
  };
  const progress = (p: JobProgress): void => {
    checkAborted();
    onProgress(p);
  };

  await mkdir(outDir, { recursive: true });
  progress({ phase: "resolving", percent: 2 });

  const warnings: string[] = [];
  const manifestEntries: ManifestEntry[] = [];
  const zipFiles: ZipFile[] = [];
  const tempFiles: string[] = [];
  const usedSources: ImagerySourceDef[] = [];
  const fileBase = safeFileBase(request.packageName);

  // ── Imagery ──────────────────────────────────────────────────────────────
  if (request.imagery) {
    const spec = request.imagery;
    const source = resolveSource(catalog, spec.sourceId);
    // License policy is server-enforced here, not just at the route layer.
    if (source.streamOnly) {
      throw new Error(
        `${source.name} is stream-only; offline packaging is not permitted by its license`,
      );
    }
    if (source.offlineRequiresPlanCheck && !spec.planConfirmed) {
      throw new Error(
        `${source.name} requires confirming your plan permits offline use (planConfirmed)`,
      );
    }
    const adapter: ImageryAdapter | undefined = adapters[source.strategy];
    if (!adapter) {
      throw new Error(`No adapter registered for strategy '${source.strategy}'`);
    }
    usedSources.push(source);

    if (spec.mode === "gpkg") {
      progress({ phase: "fetching imagery", percent: 5 });
      const pyramid = await adapter.fetchPyramid(
        source,
        request.aoi,
        spec.minZoom,
        spec.maxZoom,
        spec.tileFormat,
        {
          apiKey: spec.apiKey,
          signal,
          onProgress: (done, total) => {
            onProgress({
              phase: "fetching imagery",
              percent: 5 + Math.round((done / Math.max(1, total)) * 40),
              message: `${done}/${total} tiles`,
            });
          },
        },
      );
      warnings.push(...pyramid.warnings);
      const failRatio =
        pyramid.total > 0 ? pyramid.failed / pyramid.total : 0;
      if (failRatio > TILE_FAIL_ABORT_RATIO) {
        throw new Error(
          `Imagery fetch failed: ${pyramid.failed}/${pyramid.total} tiles failed`,
        );
      }
      if (failRatio > TILE_FAIL_WARN_RATIO) {
        warnings.push(
          `${pyramid.failed}/${pyramid.total} tiles failed to download; package has gaps`,
        );
      }

      progress({ phase: "writing geopackage", percent: 50 });
      const gpkgTemp = path.join(outDir, `${jobId}-imagery.gpkg`);
      tempFiles.push(gpkgTemp);
      writeGeoPackage({
        filePath: gpkgTemp,
        tableName: safeTableName(request.packageName),
        aoi: request.aoi,
        minZoom: spec.minZoom,
        maxZoom: spec.maxZoom,
        tiles: pyramid.tiles,
        tileFormat: spec.tileFormat,
      });
      const gpkgName = `${fileBase}.gpkg`;
      const gpkgEntry = `${uuid()}/${gpkgName}`;
      zipFiles.push({ entry: gpkgEntry, content: { file: gpkgTemp } });
      // GeoPackage import is by content sniffing — name Parameter only.
      manifestEntries.push({ zipEntry: gpkgEntry, name: gpkgName });
    } else {
      progress({ phase: "fetching imagery", percent: 5 });
      if (!adapter.fetchSingleImage) {
        throw new Error(
          `Source ${source.name} cannot produce a single rectified image for KMZ GRG export`,
        );
      }
      const image = await adapter.fetchSingleImage(
        source,
        request.aoi,
        limits.maxGrgPixels,
        { apiKey: spec.apiKey, signal },
      );
      if (!image) {
        throw new Error(`Source ${source.name} returned no image for the AOI`);
      }
      progress({ phase: "writing grg kmz", percent: 50 });
      const kmzTemp = path.join(outDir, `${jobId}-grg.kmz`);
      tempFiles.push(kmzTemp);
      await buildGrgKmz({
        filePath: kmzTemp,
        name: request.packageName,
        image: image.data,
        bounds: image.bounds,
      });
      const kmzName = `${fileBase}.kmz`;
      const kmzEntry = `${uuid()}/${kmzName}`;
      zipFiles.push({ entry: kmzEntry, content: { file: kmzTemp } });
      manifestEntries.push({
        zipEntry: kmzEntry,
        name: kmzName,
        contentType: "KML",
        visible: true,
      });
    }
  }

  // ── Features: CoT events + KML overlay ───────────────────────────────────
  progress({ phase: "writing features", percent: 65 });
  const featureByUid = new Map<string, MapFeature>(
    request.features.map((f) => [f.id, f]),
  );
  const cotFiles = buildCotEvents(request.features, input.determinism);
  for (const cot of cotFiles) {
    const entry = `${cot.uid}/${cot.uid}.cot`;
    zipFiles.push({ entry, content: cot.xml });
    manifestEntries.push({
      zipEntry: entry,
      name: featureByUid.get(cot.uid)?.name ?? cot.uid,
      uid: cot.uid,
      isCot: true,
    });
  }

  const sourcesForAttribution: ImagerySourceDef[] = [...usedSources];

  if (request.includeKmlOverlay !== false && request.features.length > 0) {
    const kml = buildKmlDocument(request.packageName, request.features);
    const entry = `${uuid()}/overlays.kml`;
    zipFiles.push({ entry, content: kml });
    manifestEntries.push({
      zipEntry: entry,
      name: "overlays.kml",
      contentType: "KML",
      visible: true,
    });
  }

  // ── Streaming map-source XML ─────────────────────────────────────────────
  progress({ phase: "writing map sources", percent: 70 });
  for (const id of request.mapSourceXmlIds) {
    const source = catalog.find((s) => s.id === id);
    if (!source) {
      warnings.push(`Skipped map-source XML for unknown source '${id}'`);
      continue;
    }
    if (!source.tileUrlTemplate) {
      warnings.push(
        `Skipped map-source XML for ${source.name}: no tile URL template`,
      );
      continue;
    }
    const keyed = source.tileUrlTemplate.includes("{key}");
    const apiKey = request.imagery?.apiKey;
    if (keyed && !(request.includeKeyInXml && apiKey)) {
      // NEVER emit keyed URLs without explicit opt-in plus a key to embed.
      warnings.push(
        `Skipped map-source XML for ${source.name}: requires an API key and includeKeyInXml opt-in`,
      );
      continue;
    }
    const xml = buildMapSourceXml(
      source,
      keyed ? { apiKey, includeKey: true } : {},
    );
    const name = `mapsource-${source.id}.xml`;
    const entry = `${uuid()}/${name}`;
    zipFiles.push({ entry, content: xml });
    manifestEntries.push({ zipEntry: entry, name });
    if (!sourcesForAttribution.some((s) => s.id === source.id)) {
      sourcesForAttribution.push(source);
    }
  }

  // ── Attribution ──────────────────────────────────────────────────────────
  const attributionEntry = `${uuid()}/attribution.txt`;
  zipFiles.push({
    entry: attributionEntry,
    content: attributionText(request.packageName, sourcesForAttribution, nowFn()),
  });
  manifestEntries.push({ zipEntry: attributionEntry, name: "attribution.txt" });

  // ── Manifest + zip ───────────────────────────────────────────────────────
  progress({ phase: "writing manifest", percent: 75 });
  const manifestXml = buildManifestXml(uuid(), request.packageName, manifestEntries);
  zipFiles.push({ entry: "MANIFEST/manifest.xml", content: manifestXml });

  progress({ phase: "zipping", percent: 85 });
  const zipPath = path.join(outDir, `${jobId}.zip`);
  await writeZip(zipPath, zipFiles);
  for (const f of tempFiles) {
    await rm(f, { force: true });
  }

  const { size } = await stat(zipPath);
  progress({ phase: "completed", percent: 100 });
  return {
    zipPath,
    sizeBytes: size,
    warnings,
    entries: zipFiles.map((f) => f.entry),
  };
}
