import { randomUUID } from "node:crypto";
import { createWriteStream } from "node:fs";
import { mkdir, rm, stat } from "node:fs/promises";
import path from "node:path";
import archiver from "archiver";
import type {
  BuildPackageInput,
  BuildPackageOutput,
  ImagerySourceDef,
  ImageryAdapter,
  JobProgress,
  ManifestEntry,
  MapFeature,
  NoteIconType,
} from "../types.js";
import { writeGeoPackage } from "./gpkg-writer.js";
import { buildGrgKmz } from "./grg-kmz.js";
import { buildManifestXml } from "./manifest.js";
import { buildCasevacEvent, buildCotEvents } from "./cot-writer.js";
import { buildKmlDocument } from "./kml-writer.js";
import { buildMapSourceXml } from "./mapsource-xml.js";
import { buildConfigPref, buildSupportCards, hasPrefContent } from "./comms-docs.js";
import { renderNoteIconPng } from "./note-icons.js";
import {
  NOTE_ICONSET_GROUP,
  buildIconsetXml,
  noteIconFile,
} from "./iconset.js";
import { buildDtedCells } from "./dted.js";
import { esc } from "./xml.js";

/**
 * Package builder — orchestrates imagery fetch, writers, manifest, and the
 * final data-package zip. All zip entry names use FORWARD slashes (ATAK
 * requires manifest zipEntry to byte-match zip paths).
 */

const TILE_FAIL_WARN_RATIO = 0.2;
const TILE_FAIL_ABORT_RATIO = 0.6;

interface ZipFile {
  /** Forward-slash zip entry path. */
  entry: string;
  content: Buffer | string | { file: string };
}

/** Filename-safe form of the package name (zip-inner file base names). */
function safeFileBase(name: string): string {
  const base = name.trim().replace(/[^A-Za-z0-9._-]+/g, "_").replace(/^_+|_+$/g, "");
  return base.length > 0 ? base : "package";
}

function safeAttachmentName(name: string): string {
  const base = path.basename(name).trim().replace(/[^A-Za-z0-9._ -]+/g, "_");
  const cleaned = base.replace(/^\.*/, "").trim();
  return cleaned.length > 0 ? cleaned : "attachment";
}

/** SQL-identifier-safe gpkg table name derived from the package name. */
function safeTableName(name: string): string {
  let t = name.toLowerCase().replace(/[^a-z0-9_]+/g, "_").replace(/^_+|_+$/g, "");
  if (!/^[a-z_]/.test(t)) t = `t_${t}`;
  return t.length > 0 ? t : "tiles";
}

function resolveSource(
  catalog: ImagerySourceDef[],
  sourceId: string,
): ImagerySourceDef {
  const source = catalog.find((s) => s.id === sourceId);
  if (!source) throw new Error(`Unknown imagery source: ${sourceId}`);
  return source;
}

/** One-line per-source attribution baked into KML descriptions (licensing policy). */
function sourceAttributionLine(s: ImagerySourceDef): string {
  return `${s.name} — Attribution: ${s.attribution} — License: ${s.license}`;
}

function includeInKmlOverlay(feature: MapFeature): boolean {
  // Every marker is a first-class editable CoT marker in ATAK (SIDC markers by
  // type, note-icon markers via the bundled iconset). A second KML point at the
  // same coordinate would duplicate labels/icons, so markers stay CoT-only.
  // Range & Bearing lines render as a native u-rb-a arrow — skip the KML copy.
  if (feature.kind === "marker") return false;
  if (feature.kind === "line" && feature.rangeBearing) return false;
  return true;
}

function attributionText(
  packageName: string,
  sources: ImagerySourceDef[],
  now: Date,
): string {
  const lines: string[] = [
    packageName,
    `Generated by TAKPack Studio on ${now.toISOString()}`,
    "",
  ];
  for (const s of sources) {
    lines.push(s.name, `Attribution: ${s.attribution}`, `License: ${s.license}`, "");
  }
  return lines.join("\n");
}

function missionBriefHtml(
  request: BuildPackageInput["request"],
  generatedAt: Date,
): string {
  const counts = new Map<string, number>();
  for (const feature of request.features) {
    counts.set(feature.kind, (counts.get(feature.kind) ?? 0) + 1);
  }
  const featureRows = request.features
    .map(
      (feature) =>
        `<tr><td>${esc(feature.kind)}</td><td>${esc(feature.name)}</td><td>${esc(feature.remarks ?? "")}</td></tr>`,
    )
    .join("");
  const countText =
    counts.size === 0
      ? "No features"
      : [...counts.entries()].map(([kind, n]) => `${n} ${kind}`).join(", ");
  return [
    "<!doctype html>",
    '<html><head><meta charset="utf-8">',
    `<title>${esc(request.packageName)} Mission Brief</title>`,
    "<style>body{font-family:Arial,sans-serif;margin:24px;line-height:1.4}table{border-collapse:collapse;width:100%}td,th{border:1px solid #999;padding:6px;text-align:left}th{background:#eee}</style>",
    "</head><body>",
    `<h1>${esc(request.packageName)} Mission Brief</h1>`,
    `<p><strong>Generated:</strong> ${esc(generatedAt.toISOString())}</p>`,
    `<p><strong>AOI:</strong> N ${request.aoi.north.toFixed(6)}, S ${request.aoi.south.toFixed(6)}, E ${request.aoi.east.toFixed(6)}, W ${request.aoi.west.toFixed(6)}</p>`,
    `<p><strong>Imagery:</strong> ${request.imagery ? `${esc(request.imagery.sourceId)} ${esc(request.imagery.mode)} z${request.imagery.minZoom}-${request.imagery.maxZoom}` : "None"}</p>`,
    `<p><strong>Features:</strong> ${esc(countText)}</p>`,
    "<h2>Feature List</h2>",
    "<table><thead><tr><th>Type</th><th>Name</th><th>Remarks</th></tr></thead><tbody>",
    featureRows || '<tr><td colspan="3">No features</td></tr>',
    "</tbody></table>",
    "</body></html>",
    "",
  ].join("\n");
}

async function writeZip(zipPath: string, files: ZipFile[]): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    const out = createWriteStream(zipPath);
    const archive = archiver("zip", { zlib: { level: 6 } });
    // Tear down both streams on error so the output fd is released — otherwise
    // the open handle can make the caller's cleanup rm() throw EBUSY on Windows.
    const fail = (err: unknown) => {
      archive.destroy();
      out.destroy();
      reject(err);
    };
    out.on("close", resolve);
    out.on("error", fail);
    archive.on("error", fail);
    archive.pipe(out);
    for (const f of files) {
      if (typeof f.content === "object" && !Buffer.isBuffer(f.content)) {
        archive.file(f.content.file, { name: f.entry });
      } else {
        archive.append(f.content, { name: f.entry });
      }
    }
    void archive.finalize();
  });
}

export async function buildPackage(
  input: BuildPackageInput,
): Promise<BuildPackageOutput> {
  const { request, jobId, outDir, catalog, adapters, limits, onProgress, signal } =
    input;
  const uuid = input.determinism?.uuid ?? randomUUID;
  const nowFn = input.determinism?.now ?? (() => new Date());

  const checkAborted = (): void => {
    if (signal?.aborted) throw new Error("Export aborted");
  };
  const progress = (p: JobProgress): void => {
    checkAborted();
    onProgress(p);
  };

  await mkdir(outDir, { recursive: true });
  progress({ phase: "resolving", percent: 2 });

  const warnings: string[] = [];
  const manifestEntries: ManifestEntry[] = [];
  const zipFiles: ZipFile[] = [];
  const tempFiles: string[] = [];
  const usedSources: ImagerySourceDef[] = [];
  const fileBase = safeFileBase(request.packageName);
  const zipPath = path.join(outDir, `${jobId}.zip`);

  try {
    // ── Imagery ────────────────────────────────────────────────────────────
    if (request.imagery) {
      const spec = request.imagery;
      const source = resolveSource(catalog, spec.sourceId);
      // License policy is server-enforced here, not just at the route layer.
      if (source.streamOnly) {
        throw new Error(
          `${source.name} is stream-only; offline packaging is not permitted by its license`,
        );
      }
      if (source.offlineRequiresPlanCheck && !spec.planConfirmed) {
        throw new Error(
          `${source.name} requires confirming your plan permits offline use (planConfirmed)`,
        );
      }
      const adapter: ImageryAdapter | undefined = adapters[source.strategy];
      if (!adapter) {
        throw new Error(`No adapter registered for strategy '${source.strategy}'`);
      }
      usedSources.push(source);

      if (spec.mode === "gpkg") {
        progress({ phase: "fetching imagery", percent: 5 });
        const pyramid = await adapter.fetchPyramid(
          source,
          request.aoi,
          spec.minZoom,
          spec.maxZoom,
          spec.tileFormat,
          {
            apiKey: spec.apiKey,
            signal,
            onProgress: (done, total) => {
              onProgress({
                phase: "fetching imagery",
                percent: 5 + Math.round((done / Math.max(1, total)) * 40),
                message: `${done}/${total} tiles`,
              });
            },
          },
        );
        warnings.push(...pyramid.warnings);
        const failRatio =
          pyramid.total > 0 ? pyramid.failed / pyramid.total : 0;
        if (failRatio > TILE_FAIL_ABORT_RATIO) {
          throw new Error(
            `Imagery fetch failed: ${pyramid.failed}/${pyramid.total} tiles failed`,
          );
        }
        if (failRatio > TILE_FAIL_WARN_RATIO) {
          warnings.push(
            `${pyramid.failed}/${pyramid.total} tiles failed to download; package has gaps`,
          );
        }

        progress({ phase: "writing geopackage", percent: 50 });
        const gpkgTemp = path.join(outDir, `${jobId}-imagery.gpkg`);
        tempFiles.push(gpkgTemp);
        writeGeoPackage({
          filePath: gpkgTemp,
          tableName: safeTableName(request.packageName),
          aoi: request.aoi,
          minZoom: spec.minZoom,
          maxZoom: spec.maxZoom,
          tiles: pyramid.tiles,
          tileFormat: spec.tileFormat,
        });
        const gpkgName = `${fileBase}.gpkg`;
        const gpkgEntry = `${uuid()}/${gpkgName}`;
        zipFiles.push({ entry: gpkgEntry, content: { file: gpkgTemp } });
        // GeoPackage import is by content sniffing — name Parameter only.
        manifestEntries.push({ zipEntry: gpkgEntry, name: gpkgName });
      } else {
        progress({ phase: "fetching imagery", percent: 5 });
        if (!adapter.fetchSingleImage) {
          throw new Error(
            `Source ${source.name} cannot produce a single rectified image for KMZ GRG export`,
          );
        }
        const image = await adapter.fetchSingleImage(
          source,
          request.aoi,
          limits.maxGrgPixels,
          { apiKey: spec.apiKey, signal },
        );
        if (!image) {
          throw new Error(`Source ${source.name} returned no image for the AOI`);
        }
        if (image.warnings?.length) warnings.push(...image.warnings);
        // The GroundOverlay LatLonBox is linear-in-degrees but the stitched
        // image is linear-in-Web-Mercator; the vertical mismatch grows with AOI
        // height and latitude (negligible for small AOIs, ~hundreds of m for a
        // 1°-tall box at mid-latitudes). Steer large areas to gpkg mode.
        if (request.aoi.north - request.aoi.south > 0.5) {
          warnings.push(
            "KMZ-GRG imagery can be vertically misregistered for tall areas; " +
              "use GeoPackage (gpkg) mode for large AOIs.",
          );
        }
        progress({ phase: "writing grg kmz", percent: 50 });
        const kmzTemp = path.join(outDir, `${jobId}-grg.kmz`);
        tempFiles.push(kmzTemp);
        await buildGrgKmz({
          filePath: kmzTemp,
          name: request.packageName,
          // Attribution travels WITH the imagery — the KMZ may be shared
          // standalone, detached from attribution.txt.
          description: sourceAttributionLine(source),
          image: image.data,
          bounds: image.bounds,
        });
        const kmzName = `${fileBase}.kmz`;
        const kmzEntry = `${uuid()}/${kmzName}`;
        zipFiles.push({ entry: kmzEntry, content: { file: kmzTemp } });
        manifestEntries.push({
          zipEntry: kmzEntry,
          name: kmzName,
          contentType: "KML",
          visible: true,
        });
      }
    }

    // ── Elevation (DTED) ───────────────────────────────────────────────────
    if (request.includeElevation) {
      progress({ phase: "fetching elevation", percent: 58 });
      const level = request.elevationLevel === 2 ? 2 : 1;
      const dted = await buildDtedCells(request.aoi, level, signal, (d, t) =>
        onProgress({
          phase: "fetching elevation",
          percent: 58 + Math.round((d / Math.max(1, t)) * 5),
          message: `${d}/${t} DTED cells`,
        }),
      );
      warnings.push(...dted.warnings);
      if (dted.files.length > 0) {
        const dtedZip = path.join(outDir, `${jobId}-dted.zip`);
        tempFiles.push(dtedZip);
        await writeZip(
          dtedZip,
          dted.files.map((f) => ({ entry: f.path, content: f.content })),
        );
        const name = "dted.zip";
        const entry = `${uuid()}/${name}`;
        zipFiles.push({ entry, content: { file: dtedZip } });
        manifestEntries.push({ zipEntry: entry, name, contentType: "DTED" });
      }
    }

    // ── Features: CoT events + KML overlay ─────────────────────────────────
    progress({ phase: "writing features", percent: 65 });
    const featureByUid = new Map<string, MapFeature>(
      request.features.map((f) => [f.id, f]),
    );
    // CoT u-d-f shapes have no interior-ring representation, so polygon holes
    // are exported solid in CoT (the KML overlay keeps them). Surface the
    // divergence rather than dropping it silently.
    const holed = request.features.filter(
      (f) =>
        (f.kind === "polygon" || f.kind === "rectangle") &&
        f.geometry.type === "Polygon" &&
        f.geometry.coordinates.length > 1,
    ).length;
    if (holed > 0) {
      warnings.push(
        `${holed} polygon(s) with holes exported as solid CoT shapes ` +
          "(holes preserved in the KML overlay only).",
      );
    }

    const cotFiles = buildCotEvents(request.features, input.determinism);
    for (const cot of cotFiles) {
      const entry = `${cot.uid}/${cot.uid}.cot`;
      zipFiles.push({ entry, content: cot.xml });
      manifestEntries.push({
        zipEntry: entry,
        name: featureByUid.get(cot.uid)?.name ?? cot.uid,
        uid: cot.uid,
        isCot: true,
      });
    }

    // Files attached to a specific feature → that marker's attachments in ATAK
    // (manifest Content carrying the marker uid, sharing the marker's folder).
    for (const f of request.features) {
      if (!f.attachments || f.attachments.length === 0) continue;
      for (const att of f.attachments) {
        const name = safeAttachmentName(att.name);
        const entry = `${f.id}/${name}`;
        const content = Buffer.from(att.base64, "base64");
        zipFiles.push({ entry, content });
        manifestEntries.push({
          zipEntry: entry,
          name,
          uid: f.id,
          ...(att.contentType ? { contentType: att.contentType } : {}),
        });
        if (content.length === 0) {
          warnings.push(`Attachment ${name} on "${f.name}" was empty.`);
        }
      }
    }

    const sourcesForAttribution: ImagerySourceDef[] = [...usedSources];

    // Every feature also exports as an editable CoT object; the KML overlay is
    // a styled visual copy for line/area geometry. Markers stay CoT-only to
    // avoid duplicate point symbols (note glyphs ride the iconset below).
    const kmlFeatures =
      request.includeKmlOverlay !== false
        ? request.features.filter(includeInKmlOverlay)
        : [];
    if (kmlFeatures.length > 0) {
      const kmlDescription =
        usedSources.length > 0
          ? usedSources.map(sourceAttributionLine).join("; ")
          : `Generated by TAKPack Studio on ${nowFn().toISOString()}`;
      const kml = buildKmlDocument(request.packageName, kmlFeatures, kmlDescription);
      const entry = `${uuid()}/overlays.kml`;
      zipFiles.push({ entry, content: kml });
      manifestEntries.push({
        zipEntry: entry,
        name: "overlays.kml",
        contentType: "KML",
        visible: true,
      });
    }

    // ── Note-icon iconset ──────────────────────────────────────────────────
    // Markers with a note glyph reference the bundled iconset by path; ship it
    // so the glyph renders on the native CoT marker (offline, no remote URLs).
    const noteIcons = [
      ...new Set(
        request.features
          .filter((f) => f.kind === "marker")
          .map((f) => f.noteIcon)
          .filter((i): i is NoteIconType => i !== undefined),
      ),
    ].sort();
    if (noteIcons.length > 0) {
      const iconsetZip = path.join(outDir, `${jobId}-iconset.zip`);
      tempFiles.push(iconsetZip);
      const iconFiles: ZipFile[] = await Promise.all(
        noteIcons.map(async (icon) => ({
          entry: `${NOTE_ICONSET_GROUP}/${noteIconFile(icon)}`,
          content: await renderNoteIconPng(icon),
        })),
      );
      await writeZip(iconsetZip, [
        { entry: "iconset.xml", content: buildIconsetXml(noteIcons) },
        ...iconFiles,
      ]);
      const name = "iconset.zip";
      const entry = `${uuid()}/${name}`;
      zipFiles.push({ entry, content: { file: iconsetZip } });
      manifestEntries.push({ zipEntry: entry, name, contentType: "iconset" });
    }

    // ── Streaming map-source XML ───────────────────────────────────────────
    progress({ phase: "writing map sources", percent: 70 });
    // The request's apiKey belongs to the imagery source's provider. It may
    // only be embedded into map-source XML for sources that share that
    // provider's keyId — never spliced into a different provider's URL.
    const imagerySpec = request.imagery;
    const imagerySource = imagerySpec
      ? catalog.find((s) => s.id === imagerySpec.sourceId)
      : undefined;
    for (const id of request.mapSourceXmlIds) {
      const source = catalog.find((s) => s.id === id);
      if (!source) {
        warnings.push(`Skipped map-source XML for unknown source '${id}'`);
        continue;
      }
      if (!source.tileUrlTemplate) {
        warnings.push(
          `Skipped map-source XML for ${source.name}: no tile URL template`,
        );
        continue;
      }
      const keyed = source.tileUrlTemplate.includes("{key}");
      const apiKey =
        source.keyId !== undefined && imagerySource?.keyId === source.keyId
          ? imagerySpec?.apiKey
          : undefined;
      if (keyed && !(request.includeKeyInXml && apiKey)) {
        // NEVER emit keyed URLs without explicit opt-in plus a key that
        // belongs to this source's provider.
        warnings.push(
          request.includeKeyInXml && imagerySpec?.apiKey
            ? `Skipped map-source XML for ${source.name}: the supplied API key belongs to a different provider`
            : `Skipped map-source XML for ${source.name}: requires an API key and includeKeyInXml opt-in`,
        );
        continue;
      }
      const xml = buildMapSourceXml(
        source,
        keyed ? { apiKey, includeKey: true } : {},
      );
      const name = `mapsource-${source.id}.xml`;
      const entry = `${uuid()}/${name}`;
      zipFiles.push({ entry, content: xml });
      manifestEntries.push({ zipEntry: entry, name });
      if (!sourcesForAttribution.some((s) => s.id === source.id)) {
        sourcesForAttribution.push(source);
      }
    }

    // ── Mission brief ──────────────────────────────────────────────────────
    if (request.includeMissionBrief) {
      const name = "mission-brief.html";
      const entry = `${uuid()}/${name}`;
      zipFiles.push({
        entry,
        content: missionBriefHtml(request, nowFn()),
      });
      manifestEntries.push({
        zipEntry: entry,
        name,
        contentType: "text/html",
      });
    }

    // ── Comms / PACE / MEDEVAC cards + config.pref + CASEVAC ────────────────
    if (request.supportDocIds && request.supportDocIds.length > 0) {
      const cards = buildSupportCards(
        request.supportDocIds,
        request.commsPlan ?? {},
        request.packageName,
        request.aoi,
      );
      for (const card of cards) {
        const name = `${card.fileBase}.html`;
        const entry = `${uuid()}/${name}`;
        zipFiles.push({ entry, content: card.html });
        manifestEntries.push({ zipEntry: entry, name, contentType: "text/html" });
      }
    }
    if (request.includePref && hasPrefContent(request.commsPlan?.identity)) {
      // ImportPrefSort matches by the .pref extension and applies on import.
      const pref = buildConfigPref(request.commsPlan!.identity!);
      const entry = `${uuid()}/config.pref`;
      zipFiles.push({ entry, content: pref });
      manifestEntries.push({
        zipEntry: entry,
        name: "config.pref",
        contentType: "ATAK Preferences",
      });
    }
    if (request.includeCasevacMarker && request.commsPlan?.medevac) {
      const center = {
        lat: (request.aoi.north + request.aoi.south) / 2,
        lon: (request.aoi.east + request.aoi.west) / 2,
      };
      const cot = buildCasevacEvent(
        request.commsPlan.medevac,
        center,
        input.determinism,
      );
      const entry = `${cot.uid}/${cot.uid}.cot`;
      zipFiles.push({ entry, content: cot.xml });
      manifestEntries.push({
        zipEntry: entry,
        name: "CASEVAC",
        uid: cot.uid,
        isCot: true,
      });
    }

    // ── User attachments ───────────────────────────────────────────────────
    if (request.attachments && request.attachments.length > 0) {
      progress({ phase: "writing attachments", percent: 72 });
      request.attachments.forEach((attachment, index) => {
        const name = safeAttachmentName(attachment.name);
        const entry = `${uuid()}/attachments/${name}`;
        const content = Buffer.from(attachment.base64, "base64");
        zipFiles.push({ entry, content });
        manifestEntries.push({
          zipEntry: entry,
          name,
          ...(attachment.contentType ? { contentType: attachment.contentType } : {}),
        });
        if (content.length === 0) {
          warnings.push(`Attachment ${index + 1} (${name}) was empty.`);
        }
      });
    }

    // ── Attribution ────────────────────────────────────────────────────────
    const attributionEntry = `${uuid()}/attribution.txt`;
    zipFiles.push({
      entry: attributionEntry,
      content: attributionText(request.packageName, sourcesForAttribution, nowFn()),
    });
    manifestEntries.push({ zipEntry: attributionEntry, name: "attribution.txt" });

    // ── Manifest + zip ─────────────────────────────────────────────────────
    progress({ phase: "writing manifest", percent: 75 });
    const manifestXml = buildManifestXml(uuid(), request.packageName, manifestEntries);
    zipFiles.push({ entry: "MANIFEST/manifest.xml", content: manifestXml });

    progress({ phase: "zipping", percent: 85 });
    // Manifest zipEntry values must each match exactly one zip entry —
    // duplicate paths (e.g. duplicate feature ids both producing
    // <uid>/<uid>.cot) would make ATAK's extractor overwrite one with the
    // other, silently losing content.
    const entryPaths = new Set<string>();
    for (const f of zipFiles) {
      if (entryPaths.has(f.entry)) {
        throw new Error(`duplicate zip entry path: ${f.entry}`);
      }
      entryPaths.add(f.entry);
    }
    await writeZip(zipPath, zipFiles);

    const { size } = await stat(zipPath);
    progress({ phase: "completed", percent: 100 });
    return {
      zipPath,
      sizeBytes: size,
      warnings,
      entries: zipFiles.map((f) => f.entry),
    };
  } catch (err) {
    // A failed/aborted build must not leave a partial artifact behind. On
    // success the zip IS the artifact, so this runs only on the error path.
    await rm(zipPath, { force: true }).catch(() => {});
    throw err;
  } finally {
    // Idempotent (rm force) — temps are removed on success and failure alike,
    // including queue timeouts: the next checkAborted() throw lands here.
    for (const f of tempFiles) {
      await rm(f, { force: true }).catch(() => {});
    }
  }
}
