import type { ImagerySourceDef, Limits } from "../types.js";

/**
 * Imagery source catalog. Licensing flags here are server-enforced:
 * `streamOnly: true` sources are rejected for gpkg/kmz-grg export and may only
 * be emitted as streaming customMapSource XML (see DESIGN.md licensing policy).
 */
export const CATALOG: ImagerySourceDef[] = [
  // ───────────── Offline-capable ─────────────
  {
    id: "usgs-imagery",
    name: "USGS Imagery",
    description: "USGS National Map high-resolution orthoimagery (US coverage)",
    category: "free",
    attribution: "U.S. Geological Survey, The National Map",
    license: "Public domain (US Government work) — offline use permitted",
    streamOnly: false,
    strategy: "xyz",
    tileUrlTemplate:
      "https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer/tile/{z}/{y}/{x}",
    usOnly: true,
    minZoom: 0,
    maxZoom: 16,
    defaultTileFormat: "jpeg",
  },
  {
    id: "usgs-topo",
    name: "USGS Topo",
    description: "USGS National Map topographic basemap (US coverage)",
    category: "free",
    attribution: "U.S. Geological Survey, The National Map",
    license: "Public domain (US Government work) — offline use permitted",
    streamOnly: false,
    strategy: "xyz",
    tileUrlTemplate:
      "https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/{z}/{y}/{x}",
    usOnly: true,
    minZoom: 0,
    maxZoom: 16,
    defaultTileFormat: "jpeg",
  },
  {
    id: "usgs-imagery-topo",
    name: "USGS Imagery + Topo",
    description: "USGS orthoimagery blended with topographic overlay (US coverage)",
    category: "free",
    attribution: "U.S. Geological Survey, The National Map",
    license: "Public domain (US Government work) — offline use permitted",
    streamOnly: false,
    strategy: "xyz",
    tileUrlTemplate:
      "https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryTopo/MapServer/tile/{z}/{y}/{x}",
    usOnly: true,
    minZoom: 0,
    maxZoom: 16,
    defaultTileFormat: "jpeg",
  },
  {
    id: "naip",
    name: "NAIP Aerial",
    description: "USDA NAIP ~0.6–1 m aerial imagery via USGS ImageServer (contiguous US)",
    category: "free",
    attribution: "USDA NAIP, U.S. Geological Survey",
    license: "Public domain (USDA NAIP) — offline use permitted",
    streamOnly: false,
    strategy: "arcgis-export",
    exportUrlBase:
      "https://imagery.nationalmap.gov/arcgis/rest/services/USGSNAIPImagery/ImageServer",
    usOnly: true,
    minZoom: 0,
    maxZoom: 18,
    defaultTileFormat: "jpeg",
  },
  {
    id: "sentinel2-pc",
    name: "Sentinel-2 (Planetary Computer)",
    description: "Lowest-cloud Sentinel-2 L2A scene from the last 12 months, global, ~10 m",
    category: "free",
    attribution: "Copernicus Sentinel data, Microsoft Planetary Computer",
    license: "Open access (Copernicus Sentinel data licence) — offline use permitted",
    streamOnly: false,
    strategy: "stac-sentinel2",
    minZoom: 0,
    maxZoom: 14,
    defaultTileFormat: "jpeg",
  },
  {
    id: "sentinel-hub",
    name: "Sentinel Hub",
    description: "Sentinel-2 L2A true-color mosaics via the Sentinel Hub Processing API",
    category: "api",
    keyId: "sentinelhub",
    keyLabel: "Client ID:Client Secret",
    keyPlaceholder: "id:secret",
    attribution: "Sentinel Hub by Sinergise — contains modified Copernicus Sentinel data",
    license: "Sentinel Hub plan terms — confirm your plan permits offline packaging",
    streamOnly: false,
    offlineRequiresPlanCheck: true,
    strategy: "sentinel-hub",
    minZoom: 0,
    maxZoom: 16,
    defaultTileFormat: "jpeg",
  },
  {
    id: "maptiler-satellite",
    name: "MapTiler Satellite",
    description: "High-resolution global satellite imagery (requires MapTiler API key)",
    category: "api",
    keyId: "maptiler",
    keyLabel: "MapTiler API Key",
    keyPlaceholder: "your_maptiler_key",
    attribution: "© MapTiler © OpenStreetMap contributors",
    license: "MapTiler terms — offline use only if your plan permits it",
    streamOnly: false,
    offlineRequiresPlanCheck: true,
    strategy: "xyz",
    tileUrlTemplate:
      "https://api.maptiler.com/tiles/satellite-v2/{z}/{x}/{y}.jpg?key={key}",
    minZoom: 0,
    maxZoom: 20,
    defaultTileFormat: "jpeg",
  },

  // ───────────── Stream-only (offline packaging forbidden) ─────────────
  {
    id: "esri-world-imagery",
    name: "Esri World Imagery",
    description: "High-resolution global satellite imagery, 30 cm in some areas",
    category: "free",
    attribution: "© Esri, Maxar, Earthstar Geographics, and the GIS User Community",
    license: "Esri Master Agreement — streaming only",
    streamOnly: true,
    strategy: "xyz",
    tileUrlTemplate:
      "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
    minZoom: 0,
    maxZoom: 19,
    defaultTileFormat: "jpeg",
  },
  {
    id: "esri-world-topo",
    name: "Esri World Topo",
    description: "Global topographic basemap",
    category: "free",
    attribution: "© Esri and contributors",
    license: "Esri Master Agreement — streaming only",
    streamOnly: true,
    strategy: "xyz",
    tileUrlTemplate:
      "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
    minZoom: 0,
    maxZoom: 19,
    defaultTileFormat: "jpeg",
  },
  {
    id: "osm-standard",
    name: "OpenStreetMap",
    description: "Standard OpenStreetMap raster tiles",
    category: "free",
    attribution: "© OpenStreetMap contributors",
    license: "OSMF tile policy forbids bulk download — streaming only",
    streamOnly: true,
    strategy: "xyz",
    tileUrlTemplate: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
    minZoom: 0,
    maxZoom: 19,
    defaultTileFormat: "png",
  },
  {
    id: "opentopomap",
    name: "OpenTopoMap",
    description: "Topographic map rendered from OSM + SRTM data",
    category: "free",
    attribution:
      "© OpenStreetMap contributors, SRTM — map style © OpenTopoMap (CC-BY-SA)",
    license: "CC-BY-SA — tile policy forbids bulk download, streaming only",
    streamOnly: true,
    strategy: "xyz",
    tileUrlTemplate: "https://tile.opentopomap.org/{z}/{x}/{y}.png",
    minZoom: 0,
    maxZoom: 17,
    defaultTileFormat: "png",
  },
  {
    id: "eox-s2cloudless",
    name: "EOX Sentinel-2 Cloudless",
    description: "Global cloudless Sentinel-2 2021 mosaic by EOX",
    category: "free",
    attribution:
      "Sentinel-2 cloudless by EOX IT Services GmbH (contains modified Copernicus Sentinel data 2021)",
    license: "CC-BY-NC-SA — streaming only",
    streamOnly: true,
    strategy: "xyz",
    tileUrlTemplate:
      "https://tiles.maps.eox.at/wmts/1.0.0/s2cloudless-2021_3857/default/g/{z}/{y}/{x}.jpg",
    minZoom: 0,
    maxZoom: 14,
    defaultTileFormat: "jpeg",
  },
  {
    id: "planet-basemaps",
    name: "Planet Basemaps",
    description: "Monthly/quarterly global mosaics at 3–5 m resolution (Planet account)",
    category: "api",
    keyId: "planet",
    keyLabel: "Client ID:Client Secret",
    keyPlaceholder: "id:secret",
    attribution: "© Planet Labs PBC",
    license: "Planet Labs — in-app preview via OAuth proxy, streaming only",
    streamOnly: true,
    strategy: "planet",
    minZoom: 0,
    maxZoom: 18,
    defaultTileFormat: "jpeg",
  },
];

export function getSource(id: string): ImagerySourceDef | undefined {
  return CATALOG.find((s) => s.id === id);
}

export const LIMITS: Limits = {
  maxTilesPerExport: 10_000,
  recommendedMaxPackageBytes: 300 * 1024 * 1024,
  maxGrgPixels: 8192,
};
